
- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/home/qp_setup_admin/Backups_UAT_During_Deployment/wpi_backup_{{ folder_date }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing wpi folder if it exists
  ansible.builtin.command: mv /opt/tomcat/wpi/ /home/qp_setup_admin/Backups_UAT_During_Deployment/wpi_backup_{{ folder_date }}
  # args:
  #   removes: /opt/tomcat/wpi/
  tags: deploy


- name: Move new files from deployment package to WPI
  ansible.builtin.copy:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/ROOT.war
    dest: /opt/tomcat/wpi/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy


