---
# roles/getInformation/tasks/main.yml

- name: Capture the logged-in user
  command: id
  register: preout
  ignore_errors: true

- name: Print user output
  debug:
    var: preout
  ignore_errors: true

- name: Stop Tomcat
  import_tasks: tomcat_stop.yml
  tags: tomcat_stop
  ignore_errors: true

- name: Start Tomcat
  import_tasks: tomcat_start.yml
  ignore_errors: true
  tags: tomcat_start

- name: Backup and Deploy
  import_tasks: wpi_deploy_root.yml
  tags: deploy
  ignore_errors: true

- name: Apply property file for deployment
  import_tasks: wpi_property_file.yml
  tags: wpi_propsuat_copy
  ignore_errors: true

- name: SFTP connection
  import_tasks: download_artifact.yml
  tags: download_artifact
  ignore_errors: true