
- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing rakins folder if it exists
  ansible.builtin.command: mv /opt/tomcat/rakins/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}
  # args:
  #   removes: /opt/tomcat/rakins/
  tags: deploy

- name: Create rakins folder
  ansible.builtin.file :
    path: /opt/tomcat/rakins/
    state: directory
    recurse: yes
    owner: apache
    group: apache
    mode: '0644'
  tags: deploy


- name: Move new files from deployment package to Tomcat webapps
  ansible.builtin.copy:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/ROOT.war
    dest: /opt/tomcat/rakins/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy


- name: Backup existing rakinsurance folder if it exists
  ansible.builtin.command: mv /var/www/html/rakinsurance/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}
  tags: deploy


- name: Create Rakinsurance folder
  ansible.builtin.file :
    path: /var/www/html/rakinsurance/
    state: directory
    recurse: yes
    owner: apache
    group: apache
    mode: '0644'
  tags: deploy


- name: Reformat date to DDMMYYYY format
  set_fact:
    zip_date: >-
      {{ (ansible_date_time.date | regex_replace('-', ''))[6:8]
         + (ansible_date_time.date | regex_replace('-', ''))[4:6]
         + (ansible_date_time.date | regex_replace('-', ''))[0:4] }}
  tags: deploy


- name: Unarchive rak-uat ZIP with today's date
  ansible.builtin.unarchive:
    src: "/home/qp_setup_admin/UAT_Deployment_Package/{{ deploy_dir }}/rak-uat-{{ zip_date }}.zip"
    dest: /var/www/html/rakinsurance/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy



# - name: Move new files from deployment package to Tomcat webapps
#   ansible.builtin.unarchive:
#     src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/rak-uat-*.zip
#     dest: /var/www/html/rakinsurance/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy

# - name: Set ownership and permissions on new ROOT.war
#   ansible.builtin.file:
#     path: /opt/tomcat/rakins/ROOT.war
#     owner: apache
#     group: apache
#     mode: '0644'
#   tags: deploy