


- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ ansible_date_time.iso8601_basic_short }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing rakins folder
  ansible.builtin.command: mv /opt/tomcat/rakins/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ ansible_date_time.iso8601_basic_short }}
  args:
    removes: /opt/tomcat/rakins/
  tags: deploy
  
- name: Backup existing rakinsurance folder
  ansible.builtin.command: mv /var/www/html/rakinsurance /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ ansible_date_time.iso8601_basic_short }}
  args:
    removes: /var/www/html/rakinsurance
  tags: deploy

- name: Move new files from deployment package to Tomcat webapps
  ansible.builtin.copy:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/
    dest: /opt/tomcat/rakins/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy
  
  
- name: Unzip rak-uat-date.zip into the same folder
  ansible.builtin.unarchive:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}//rak-uat-{{ deploy_date }}.zip
    dest: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/
    remote_src: yes
  become: true
  

  

 
