
- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/opt/tomcat/backup_{{ ansible_date_time.iso8601_basic_short }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing ROOT.war if it exists
  ansible.builtin.command: mv /opt/tomcat/rakins/ROOT.war /opt/tomcat/backup_{{ ansible_date_time.iso8601_basic_short }}/ROOT.war
  args:
    removes: /opt/tomcat/rakins/ROOT.war
  tags: deploy

- name: Move new ROOT.war from deployment package to Tomcat webapps
  ansible.builtin.copy:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/ROOT.war
    dest: /opt/tomcat/rakins/ROOT.war
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy
 

# - name: Set ownership and permissions on new ROOT.war
#   ansible.builtin.file:
#     path: /opt/tomcat/rakins/ROOT.war
#     owner: apache
#     group: apache
#     mode: '0644'
#   tags: deploy