
- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing rakins folder if it exists
  ansible.builtin.command: mv /opt/tomcat/rakins/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}
  # args:
  #   removes: /opt/tomcat/rakins/
  tags: deploy

- name: Move new files from deployment package to Tomcat webapps
  ansible.builtin.copy:
    src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/ROOT.war
    dest: /opt/tomcat/rakins/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy

# - name: Backup existing rakinsurance folder if it exists
#   ansible.builtin.command: mv /var/www/html/rakinsurance/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}
#   args:
#     removes: /var/www/html/rakinsurance/
#   tags: deploy


# - name: Extract deployment date from deployment directory
#   set_fact:
#     deploy_date: "{{ deploy_dir.split('_')[-1] }}"
#   tags: deploy
 

# - name: Set ownership and permissions on new ROOT.war
#   ansible.builtin.file:
#     path: /opt/tomcat/rakins/ROOT.war
#     owner: apache
#     group: apache
#     mode: '0644'
#   tags: deploy