
# - name: Create backup directory with timestamp
#   ansible.builtin.file:
#     path: "/home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}"
#     state: directory
#     mode: '0755'
#   tags: deploy

- name: Ensure local target directory exists
  ansible.builtin.file:
    path: "{{ local_target }}"
    state: directory
    mode: '0755'

- name: Download artifact folder using SFTP
  ansible.builtin.shell: |
    sshpass -p '{{ sftp_pass }}' sftp {{ sftp_user }}@{{ sftp_host }} <<EOF
    lcd {{ local_target }}
    cd "/SIMS_Folder/SIMS_UAT/Deployment_Package/"
    mget -r *
    bye
    EOF
  args:
    executable: /bin/bash