

- name: Backup existing rakins folder if it exists
  ansible.builtin.command: mv /var/www/html/rakinsurance /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ ansible_date_time.iso8601_basic_short }}
  args:
    removes: /var/www/html/rakinsurance/
  tags: deploy

- name: Extract deployment date from deployment directory
  set_fact:
    deploy_date: "{{ deploy_dir.split('_')[-1] }}"
  tags: unzip

- name: Unzip rak-uat zip file dynamically
  ansible.builtin.unarchive:
    src: "/home/qp_setup_admin/UAT_Deployment_Package/{{ deploy_dir }}/rak-uat-{{ deploy_date }}.zip"
    dest: "/var/www/html/rakinsurance/"
    remote_src: yes
  tags: unzip

