

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /var/www/html/rakinsurance/
    state: directory
    mode: '0755'


- name: Unzip rak-uat zip file dynamically
  ansible.builtin.unarchive:
    src: "/home/qp_setup_admin/UAT_Deployment_Package/{{ deploy_dir }}/rak-uat-{{ deploy_date }}.zip"
    dest: "/var/www/html/rakinsurance/"
    remote_src: yes
  tags: unzip

