- name: Locate latest backup folder
  ansible.builtin.find:
    paths: /home/qp_setup_admin/Backups_UAT_During_Deployment/
    file_type: directory
    patterns: '^wpi_backup_.*'
    use_regex: true
  register: wpi_backup_dirs
  tags: deploy

- name: Set latest backup path
  set_fact:
    latest_backup_path: "{{ wpi_backup_dirs.files | sort(attribute='mtime', reverse=true) | first }}"
  when: wpi_backup_dirs.matched > 0
  tags: deploy

- name: Move ROOT.war from latest backup to Tomcat webapps
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/wpi/ROOT.war"
    dest: /opt/tomcat/wpi/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy

- name: Start Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
  become: true

- name: Wait for 2 minutes before copying propsuat folder
  ansible.builtin.pause:
    minutes: 2
  tags: wpi_propsuat_copy

- name: Stop Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: stopped
  become: true


- name: Copy propsuat folder from backup to target
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/wpi/ROOT/WEB-INF/classes/propsuat/"
    dest: /opt/tomcat/wpi/ROOT/WEB-INF/classes/propsuat/
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes
  become: true
  tags: wpi_propsuat_copy

- name: Start Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
  become: true


