- name: Stop Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: stopped
  become: true


- name: Copy propsuat folder from backup to target
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/wpi/ROOT/WEB-INF/classes/propsuat/"
    dest: /opt/tomcat/wpi/ROOT/WEB-INF/classes/
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes
  become: true
  tags: wpi_propsuat_copy

- name: Start Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
  become: true
