- name: Locate latest backup folder
  ansible.builtin.find:
    paths: /home/qp_setup_admin/Backups_UAT_During_Deployment/
    file_type: directory
    patterns: '^backup_.*'
    use_regex: true
  register: backup_dirs
  tags: deploy

- name: Set latest backup path
  set_fact:
    latest_backup_path: "{{ backup_dirs.files | sort(attribute='mtime', reverse=true) | first }}"
  when: backup_dirs.matched > 0
  tags: deploy

- name: Move ROOT.war from latest backup to Tomcat webapps
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/rakins/ROOT.war"
    dest: /opt/tomcat/rakins/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy

- name: Copy rakinsurance from latest backup to html folder
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/rakinsurance/"
    dest: /var/www/html/rakinsurance/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  tags: deploy


# - name: Move ROOT.war file from today's backup folder to Tomcat webapps
#   ansible.builtin.copy:
#     src: /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}/rakins/ROOT.war
#     dest: /opt/tomcat/rakins/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy


# - name: Copy rakinsurance from backup into html/rakinsurance folder
#   ansible.builtin.copy:
#     src: /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}/rakinsurance/
#     dest: /var/www/html/rakinsurance/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy


# - name: Backup existing rakinsurance folder if it exists
#   ansible.builtin.command: mv /var/www/html/rakinsurance/ /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}
#   tags: deploy


# - name: Create Rakinsurance folder
#   ansible.builtin.file :
#     path: /var/www/html/rakinsurance/
#     state: directory
#     recurse: yes
#     owner: apache
#     group: apache
#     mode: '0644'
#   tags: deploy


# - name: Extract deployment date from deploy_dir
#   set_fact:
#     zip_date: "{{ deploy_dir | regex_search('\\d{8}') }}"
#   tags: deploy



# - name: Unarchive rak-uat ZIP with today's date
#   ansible.builtin.unarchive:
#     src: "/home/qp_setup_admin/UAT_Deployment_Package/{{ deploy_dir }}/rak-uat-{{ zip_date }}.zip"
#     dest: /var/www/html/rakinsurance/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy

# - name: Copy fixedfiles from backup into new rakinsurance folder
#   ansible.builtin.copy:
#     src: /home/qp_setup_admin/Backups_UAT_During_Deployment/backup_{{ folder_date }}/rakinsurance/fixedfiles/
#     dest: /var/www/html/rakinsurance/fixedfiles/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy


# - name: Set ownership of rakinsurance folder to apache 
#   ansible.builtin.file:
#     path: /var/www/html/rakinsurance/
#     owner: apache
#     group: apache
#     recurse: yes
#   tags: deploy

# - name: Move new files from deployment package to Tomcat webapps
#   ansible.builtin.unarchive:
#     src: /home/qp_setup_admin/UAT_Deployment_Package/{{deploy_dir}}/rak-uat-*.zip
#     dest: /var/www/html/rakinsurance/
#     owner: apache
#     group: apache
#     mode: '0644'
#     remote_src: yes
#   tags: deploy

# - name: Set ownership and permissions on new ROOT.war
#   ansible.builtin.file:
#     path: /opt/tomcat/rakins/ROOT.war
#     owner: apache
#     group: apache
#     mode: '0644'
#   tags: deploy