---
# roles/getInformation/tasks/main.yml

- name: Capture the logged-in user
  command: id
  register: preout
  ignore_errors: true

- name: Print user output
  debug:
    var: preout
  ignore_errors: true

- name: Stop HTTPD
  import_tasks: httpd_stop.yml
  tags: httpd_stop
  ignore_errors: true

- name: Stop Tomcat
  import_tasks: tomcat_stop.yml
  tags: tomcat_stop
  ignore_errors: true

- name: Start Tomcat
  import_tasks: tomcat_start.yml
  ignore_errors: true
  tags: tomcat_start

- name: Rollback
  import_tasks: rollback.yml
  tags: deploy
  ignore_errors: true

- name: Start HTTPD
  import_tasks: httpd_start.yml
  tags: httpd_start
  ignore_errors: true

