- name: Locate latest backup folder
  ansible.builtin.find:
    paths: /home/qp_setup_admin/Backups_UAT_During_Deployment/
    file_type: directory
    patterns: '^backup_.*'
    use_regex: true
  register: backup_dirs

- name: Set latest backup path
  set_fact:
    latest_backup_path: "{{ backup_dirs.files | sort(attribute='mtime', reverse=true) | first }}"
  when: backup_dirs.matched > 0

# - name: Stop Tomcat service
#   ansible.builtin.service:
#     name: tomcat
#     state: stopped
#   become: true

- name: Delete ROOT folder from rakins
  ansible.builtin.file:
    path: "/opt/tomcat/rakins/ROOT/"
    state: absent

- name: Delete ROOT.war file from rakins
  ansible.builtin.file:
    path: "/opt/tomcat/rakins/ROOT.war"
    state: absent


- name: Move ROOT.war from latest backup to Tomcat webapps
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/rakins/ROOT.war"
    dest: /opt/tomcat/rakins/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes

- name: TOMCAT START
  systemd: 
    name: tomcat
    state: started

- name: Wait for 3 minutes before copying propsuat folder
  ansible.builtin.pause:
    minutes: 2

- name: Stop Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: stopped
  become: true

- name: Copy propsuat folder from backup to target
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/rakins/ROOT/WEB-INF/classes/propsuat/"
    dest: /opt/tomcat/rakins/ROOT/WEB-INF/classes/propsuat/
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes
  become: true


- name: Start Tomcat service
  ansible.builtin.service:
    name: tomcat
    state: started
  become: true

- name: Wait for 3 minutes before copying propsuat folder
  ansible.builtin.pause:
    minutes: 2

- name: httpd STOP 
  systemd: 
    name: httpd
    state: stopped

- name: Delete ROOT.war file from rakins
  ansible.builtin.file:
    path: "/var/www/html/rakinsurance/"
    state: absent


- name: Delete ROOT.war file from rakins
  ansible.builtin.file:
    path: "/var/www/html/rakinsurance/"
    state: directory

- name: Copy rakinsurance from latest backup to html folder
  ansible.builtin.copy:
    src: "{{ latest_backup_path.path }}/rakinsurance/"
    dest: /var/www/html/rakinsurance/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes

- name: httpd START
  systemd: 
    name: httpd
    state: started

