- name: Create backup directory with timestamp
  ansible.builtin.file:
    path: "/opt/tomcat/backup_{{ ansible_date_time.iso8601_basic_short }}"
    state: directory
    mode: '0755'
  tags: deploy

- name: Backup existing ROOT.war if it exists
  ansible.builtin.command: mv /opt/tomcat/rakins/ROOT.war /opt/tomcat/backup_{{ ansible_date_time.iso8601_basic_short }}/ROOT.war
  args:
    removes: /opt/tomcat/rakins/ROOT.war
  ignore_errors: yes
  tags: deploy

- name: Backup existing ROOT directory if it exists
  ansible.builtin.command: mv /opt/tomcat/rakins/ROOT /opt/tomcat/backup_{{ ansible_date_time.iso8601_basic_short }}/ROOT
  args:
    removes: /opt/tomcat/rakins/ROOT
  ignore_errors: yes
  tags: deploy

- name: Copy new ROOT.war for deployment
  ansible.builtin.copy:
    src: /home/qp_setup_admin/Prod_Deployment_Package/Deploy_Datetime/ROOT.war
    dest: /opt/tomcat/rakins/ROOT.war
    owner: tomcat
    group: tomcat
    mode: '0644'
  tags: deploy
