- name:       "CAPTURE USER LOGGED IN"
  command:    "id"
  register:   preout
  ignore_errors: true


- name: Print USER OUTPUT
  debug:
    var: preout
  ignore_errors: true

 
- name:   "TOMCAT STOP"
  import_tasks: tomcat_stop.yml
  ignore_errors: true
  tags: tomcat_stop


- name:   "TOMCAT START"
  import_tasks: tomcat_start.yml
  ignore_errors: true
  tags: tomcat_start 