name: GET-HOST-INFORMATION
on:
  workflow_dispatch:


jobs:
  ANSIBLE-TEST:
    runs-on:
      labels: uatcicd     
    # needs: [CONFIRM-TO-PROCEED] 
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd       

      - name: GET INFORMATION
        run: |
          ansible-playbook -b --extra-vars  'target=RIC-CICD-RUNNER'  playbook/getInformation.yml
