name: TOMCAT-STOP-START
on:
  workflow_dispatch:


jobs:
  ANSIBLE-TEST:
    runs-on:
      labels: uatcicd     
    # needs: [CONFIRM-TO-PROCEED] 
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd       

      - name: TOMCAT STOP
        run: |
          ansible-playbook -b --extra-vars  'target=ROC-UATVINYLPLUS'  playbook/getInformation.yml --tags tomcat_stop

      - name: TOMCAT START 
        run: |
          ansible-playbook -b --extra-vars  'target=ROC-UATVINYLPLUS'  playbook/getInformation.yml --tags tomcat_start
