name: UAT-RAKINSURANCE-DEPLOYMENT-ROLLBACK

on:
  workflow_dispatch:
    # inputs:
    #   deployment_directory: 
    #     description: Enter the directory to be Rollback
    #     required: true
    #     default: Deploy_UAT_27052025

jobs:

  STOP_TOMCAT:
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd

      - name: TOMCAT STOP
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurDeploymentRollback.yml --tags tomcat_stop
  

  BACKUP_DEPLOY_COPY:
    needs: [STOP_TOMCAT]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Copy and Deploy ROOT.war to rakins folder
        run: |
          DATE=$(date +'%Y-%m-%d')-"${{ github.run_id }}"
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e deploy_dir="${{ github.event.inputs.deployment_directory }}" -e folder_date="${DATE}" playbook/uatRakInsurDeploymentRollback.yml --tags deploy



  TOMCAT_START:
    needs: [BACKUP_DEPLOY_COPY]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: TOMCAT START
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurDeploymentRollback.yml --tags tomcat_start



  HTTPD_STOP:
    needs: [TOMCAT_START]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: HTTPD STOP
        run: |
          ansible-playbook -b \--extra-vars 'target=ROC-UATVINYLPLUS' \playbook/uatRakInsurDeploymentRollback.yml --tags httpd_stop


 
  
  # UNZIP_RAK_UAT_FILE:
  #   needs: [BACKUP_DEPLOY]
  #   runs-on: 
  #     labels: cicduatrunner
  #   steps:
  #     - name: Unzip RAK UAT folder
  #       run: |
  #         ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e deploy_dir="${{ github.event.inputs.deployment_directory }}" playbook/uatRakInsurDeployment.yml --tags unzip


  
  HTTPD_START:
    needs: [HTTPD_STOP]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: HTTPD START
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurDeployment.yml --tags httpd_start



  # PROPSUAT_COPY:
  #   needs: [HTTPD_START]
  #   runs-on:
  #     labels: cicduatrunner
  #   steps:
  #   - name: Copy propsuat from backup and restart Tomcat
  #     run: |
  #       DATE=$(date +'%Y-%m-%d')-"${{ github.run_id }}"
  #       ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e folder_date="${DATE}" playbook/uatRakInsurDeployment.yml --tags propsuat_copy

  