name: UAT-WPI-RAKEZ-DEPLOYMENT

on:
  workflow_dispatch:
    inputs:
      wpi_deployment_directory: 
        description: Enter the directory to be deployed
        required: true
        default: Deploy_WPI_UAT_30042025


jobs:

  DOWNLOAD_ARTIFACT:
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd      
      - name: DOWNLOAD ARTIFACT
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e wpi_deploy_dir="${{ github.event.inputs.wpi_deployment_directory }}"  playbook/uatRakInsurWPIDeployment.yml --tags download_artifact


  STOP_TOMCAT:
    needs: [DOWNLOAD_ARTIFACT]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd

      - name: TOMCAT STOP
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurWPIDeployment.yml --tags tomcat_stop
  
  BACKUP_DEPLOY:
    needs: [STOP_TOMCAT]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: BACKUP, DEPLOY ROOT.war 
        run: |
          DATE=$(date +'%Y-%m-%d')-"${{ github.run_id }}"
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e wpi_deploy_dir="${{ github.event.inputs.wpi_deployment_directory }}" -e folder_date="${DATE}" playbook/uatRakInsurWPIDeployment.yml --tags deploy

          
  TOMCAT_START:
    needs: [BACKUP_DEPLOY]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: TOMCAT START
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurWPIDeployment.yml --tags tomcat_start



  PROPSUAT_COPY:
    needs: [TOMCAT_START]
    runs-on:
      labels: cicduatrunner
    steps:
    - name: Copy propsuat from backup and restart Tomcat
      run: |
        DATE=$(date +'%Y-%m-%d')-"${{ github.run_id }}"
        ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e wpi_deploy_dir="${{ github.event.inputs.wpi_deployment_directory }}" -e folder_date="${DATE}" playbook/uatRakInsurWPIDeployment.yml --tags propsuat_copy

  