name: UAT-RAKINSURANCE-DEPLOYMENT-ROLLBACK

on:
  workflow_dispatch:
    # inputs:
    #   deployment_directory: 
    #     description: Enter the directory to be Rollback
    #     required: true
    #     default: Deploy_UAT_27052025

jobs:

  STOP_TOMCAT:
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: List Files
        run: |
          ls -tlr
          pwd

      - name: TOMCAT STOP
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurDeploymentRollback.yml --tags tomcat_stop
  

  BACKUP_DEPLOY_COPY:
    needs: [STOP_TOMCAT]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: Copy and Deploy ROOT.war to rakins folder
        run: |
          DATE=$(date +'%Y-%m-%d')-"${{ github.run_id }}"
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' -e deploy_dir="${{ github.event.inputs.deployment_directory }}" -e folder_date="${DATE}" playbook/uatRakInsurDeploymentRollback.yml --tags deploy



  TOMCAT_START:
    needs: [BACKUP_DEPLOY_COPY]
    runs-on: 
      labels: cicduatrunner
    steps:
      - name: TOMCAT START
        run: |
          ansible-playbook -b --extra-vars 'target=ROC-UATVINYLPLUS' playbook/uatRakInsurDeploymentRollback.yml --tags tomcat_start

